services:   

  web:   
    image: mon-image-php  
    ports:   
      - "80:80"   
    volumes:   
      - ./mon-site:/var/www/html   
      - ./apache-conf/000-default.conf:/etc/apache2/sites-enabled/000-default.conf   
    depends_on:    
      - db   

  db:   
    image: mysql:5.7   
    environment:   
      MYSQL_ROOT_PASSWORD: root   
      MYSQL_DATABASE: mydb   
      MYSQL_USER: user   
      MYSQL_PASSWORD: password   
    ports:   
      - "3306:3306"  
    volumes:  
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
